### ISSUE TITLE
Add eslint

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#103]
The goal of this ticket is to add eslint with reasonable set of rules. By reasonable set of rules I mean rules that we can satisfy in  short amount of time (e.g. spend 0.5 workday to fix). The idea is that if we have too many rules that are failing at the same time everybody will ignore them. We should follow this issue by iterative process of adding new reasonable sets of rules again and 
 again and satisfying it ASAP.
 
 Other "save strategy" could be to validate only modified files, which we can discuss :).

A/C:
- [x] set up project with eslint
- [x] describe eslint rules
- [x] discuss and decide which rules to use
- [x] implement agreed rules as warnings

**Comment by shellyear** [comment]
Hi, @blcham do we want to apply some typescript eslint rules or plugins in advance ? They will not be applied immediately, because the whole codebase is written in js, but they will become beneficial as soon, as we migrate to typescript.

But as for now, I will continue the implementation of the eslint js rules only

**Comment by blcham** [comment]
> do we want to apply some typescript eslint rules or plugins in advance ? 

No, pls follow the steps define in this ticket so we do it incrementally.

**Comment by shellyear** [comment]
I will leave a link here, explaining the things that I've added to the .eslintrc.js [here](https://chat.openai.com/share/9d6293da-32b1-4c0a-8647-fbe69ca1b83f).  Let me know if the link doesn't work, I will write it down manually

Plugins that I plan to add:

**eslint-plugin-react-hooks**: a plugin with rules for React hooks. It will ensure that you never use a React hook outside of a function component.

**eslint-plugin-import**: a plugin to enable ESLint to handle ES6+ import/export syntax.

_@typescript-eslint/parser_: a code parser for TypeScript (Important: I plan to add it after migration to ts)

the list might be updated over time

**Comment by shellyear** [comment]
Here is my eslint config that I used for one of my pet projects (typescript react), it was inspired by my previous working experince, and discussions about the rules. Some of the airbnb rules may be good for us (depends on the team preferences), so they can be overwritten in the _rules_  section 

[eslintrc (1).txt](https://github.com/kbss-cvut/record-manager-ui/files/14501605/eslintrc.1.txt)

**Comment by shellyear** [comment]
Explanation of the current (basic) plugins are [here](https://chat.openai.com/share/9d6293da-32b1-4c0a-8647-fbe69ca1b83f)

Plugins to be added: 

- [eslint-plugin-react-refresh](https://www.npmjs.com/package/eslint-plugin-react-refresh) - 
- eslint-plugin-react-hooks: a plugin with rules for React hooks. It will ensure that you never use a React hook outside of a function component.

The list might be updated over time, as well as some rules defined in airbnb config might be overwritten.

also rules for  can be overwritten in the _rules_ section of the .eslintrc.js

Here is my config that I used in one of my pet projects, and it was inspired by my previous experince working on project with a large codebase (note: it was in typescript, but there aren't significant differences in eslint rules for ts and js)

**Comment by blcham** [comment]
Thanks, looks good.  Can I run it already? (see my comment https://github.com/kbss-cvut/record-manager-ui/pull/109#issuecomment-1980305255)

**Comment by shellyear** [comment]
Now we have prop-types used in the project, and after migration to ts, I want use types or interface for defining types for the props. But for now I will will just defines propTypes for that Class 
![Uploading Screenshot 2024-03-06 at 14.05.22.png…]()
