### ISSUE TITLE
Resolve remaining build warnings

### ISSUE THREAD

**Issue by shellyear** [kbss-cvut/record-manager-ui#113]
Fix remaining warnings left in [here](https://github.com/kbss-cvut/record-manager-ui/pull/109) 

Note: remaining warnings left after npm run validate are actually build-related. I've also included fixes of runtime errors shown in the browser, I can cherry-pick to a separate branch if needed.

solving in this [PR](https://github.com/kbss-cvut/record-manager-ui/pull/116)

Warnings: 
- [x] 1) https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility
https://github.com/vitejs/vite/issues/9200
<img width="862" alt="Screenshot 2024-03-06 at 19 20 34" src="https://github.com/kbss-cvut/record-manager-ui/assets/50382323/02aa01e2-1eb1-471a-bedf-e7f1f0d391bd">

- [x] 2) UPD: seems to be related to rollup, not the eslint
<img width="867" alt="Screenshot 2024-03-06 at 19 22 32" src="https://github.com/kbss-cvut/record-manager-ui/assets/50382323/052df59f-e3ff-40fe-ab20-dddb0c2c08cd">

- [x] 3) UPD: https://github.com/evanw/esbuild/issues/3016,  https://stackoverflow.com/questions/1690642/purpose-of-asterisk-before-a-css-property
<img width="885" alt="Screenshot 2024-03-06 at 19 23 17" src="https://github.com/kbss-cvut/record-manager-ui/assets/50382323/5bcdb85f-b2ea-411b-8b7a-4e71ad1b5a01">

- [x] 4) 
<img width="666" alt="Screenshot 2024-03-06 at 19 46 46" src="https://github.com/kbss-cvut/record-manager-ui/assets/50382323/495c5e68-700d-47d0-80a1-5fdc63e5957b">

- [x] 5) 
<img width="987" alt="Screenshot 2024-03-08 at 11 18 12" src="https://github.com/kbss-cvut/record-manager-ui/assets/50382323/a11547dd-8298-46a2-a128-94d8aa2a9171">

**Comment by shellyear** [comment]
It seems that the 3rd error is related to [datatables.net](https://datatables.net/) package

**Comment by blcham** [comment]
@LaChope note that some of the issues created in https://github.com/kbss-cvut/record-manager-ui/pull/109 were not resolved yet and when running eslint it might give you warning as described here.

**Comment by shellyear** [comment]
The [2] warning is related to the @kbss-cvut/s-forms package, in the dist folder of this module in s-forms.modern.js this error appears _"node_modules/@kbss-cvut/s-forms/dist/s-forms.modern.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues."._ 

Options:
1) We can solve it by defining the rollup.config.js and ignore these errors
2) Or try to solve the root cause in the @kbss-cvut/s-forms package

**Comment by shellyear** [comment]
> From [this discussion](https://stackoverflow.com/questions/68187576/whats-the-meaning-of-pure-in-some-javascript-source-code), I think it can be simply ignored (configured so that we don't see this message anymore).

ok, thanks, I'll try to filter them out via rollup config

**Comment by shellyear** [comment]
Hi, @blcham, @LaChope. All the errors were either fixed or filtered out from showing, also the [5] warning is related to _store_ npm package being used in the dependencies in @kbss-cvut/s-forms@0.7.1-beta-48c6cc4.0
<img width="876" alt="Screenshot 2024-03-08 at 11 18 48" src="https://github.com/kbss-cvut/record-manager-ui/assets/50382323/f12a2b74-477e-4ce7-a824-2fbcb1c92103">

**Comment by shellyear** [comment]
@blcham  [5] error:  node_modules/store/plugins/lib/json2.js (493:20) Use of eval in "node_modules/store/plugins/lib/json2.js" is strongly discouraged as it poses security risks and may cause issues with minification.   
It relates to the "store" package. If you run **npm ls store** you'll it is related to one of the @kbss-cvut/s-forms deeper packages
![Uploading Screenshot 2024-03-13 at 21.21.03.png…]()

**Comment by shellyear** [comment]
@blcham 
[1] fixed - was solved by using pofyliss in aliases in vite.config.js
[2] in progress -  the root cause need to be solved
[3] in progress -  the root cause need to be solved
[4] fixed- common runtime error, fixed proptypes
[5.1] fixed - "can't be bundle without module attribute" - fixed by using slash in src="/config.js" - works with docker, build and dev
[5.2] - in progress - relates to "store" package used in @kbss-cvut/s-forms

**Comment by shellyear** [comment]
The [2] error is a result of tree shaking made by rollup in vite. 
_In "node_modules/@kbss-cvut/s-forms/dist/s-forms.modern.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues._
[%](https://rollupjs.org/configuration-options/#treeshake-manualpurefunctions)

**Comment by shellyear** [comment]
> Hi, @blcham, @LaChope. All the errors were either fixed or filtered out from showing, also the [5.1] warning is related to _store_ npm package being used in the dependencies in @kbss-cvut/s-forms@0.7.1-beta-48c6cc4.0 <img alt="Screenshot 2024-03-08 at 11 18 48" width="876" src="https://private-user-images.githubusercontent.com/50382323/311199092-f12a2b74-477e-4ce7-a824-2fbcb1c92103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjU4MjEsIm5iZiI6MTcxMDQyNTUyMSwicGF0aCI6Ii81MDM4MjMyMy8zMTExOTkwOTItZjEyYTJiNzQtNDc3ZS00Y2U3LWE4MjQtMmZiY2IxYzkyMTAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE0MTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZThkY2QwZmFmOGFiMmI5MjVmNjUyOTQxMWQ5NzM1NThiY2Y1ZWMzZTQ2NTgzYjBkM2E5MDAyYTMwNDk2MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H1Qp_tBvbTDUJIlZVVOWd-FjSifr9NEbY54HjCgFKao">
> 
> I'll filter this out in vite.config.js and leave a comment in the code referencing this issue

[5.2]  _Use of eval in "node_modules/store/plugins/lib/json2.js" is strongly discouraged as it poses security risks and may cause issues with minification_ 

The root cause is the "eval" function being used  inside node_modules/store/plugins/lib/json2.js. The "store" package is being used inside of @kbss-cvut/s-forms, in one of it's dependencies. So the solution will be to not rely on packages that use eval, or just simply filter out this error. Also eval by itself [is not recommended](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval) to use in js, due to security issues

**Comment by shellyear** [comment]
[3] https://vitejs.dev/guide/features#postcss

**Comment by shellyear** [comment]
> It seems that the [3] error is related to [datatables.net](https://datatables.net/) package
[3]
<img width="1427" alt="Screenshot 2024-03-14 at 18 37 44" src="https://github.com/kbss-cvut/record-manager-ui/assets/50382323/fdd90673-00b4-4eda-aa64-e02e45181895">

**Comment by blcham** [comment]
Good job, regarding [3] i suggest to filter the error with comment in source code pointing to https://github.com/kbss-cvut/s-forms/issues/283
