### ISSUE TITLE
Husky error when using script 'npm run install'

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/record-manager-ui#115]
When running `npm install`, Husky throws this error:

![Image](https://github.com/kbss-cvut/record-manager-ui/assets/57750426/79663986-c2d3-451b-a8b4-5d5a47254fef)

@blcham @shellyear

**Comment by shellyear** [comment]
Looks weird, don't have this error on my main branch

**Comment by LaChope** [comment]
My bad, I did not run `npm run prepare`... Closing the ticket.
