### ISSUE TITLE
Delete record modal causes crash

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/record-manager-ui#124]
@blcham 
In the Records view, when trying to delete a record, the application crashes. It seems to be caused by the Modal component from React-bootstrap.

Tested on latest commit of main branch (8a569ea7)

![Image](https://github.com/kbss-cvut/record-manager-ui/assets/57750426/a69c57fa-5cdb-4480-b3b5-fe0f59de3152)

![Image](https://github.com/kbss-cvut/record-manager-ui/assets/57750426/e5c3b34a-90a4-41c2-ad0d-bc2f7a6a7873)

**Comment by blcham** [comment]
@shellyear, can it be a bad merge of the functionality?

**Comment by LaChope** [comment]
@blcham I think not, I noticed because I tried on my branch which is using older version (before eslint) and was also crashing

**Comment by LaChope** [comment]
@blcham @shellyear Important information, happens only with Firefox, with Chrome, it works fine.

**Comment by blcham** [comment]
FYI, just that you know @ledsoft (do not need to comment)

**Comment by ledsoft** [comment]
This looks the same, but sadly no fix is provided. https://github.com/facebookarchive/draft-js/issues/1916

**Comment by shellyear** [comment]
> @blcham @shellyear Important information, happens only with Firefox, with Chrome, it works fine.

@blcham  @LaChope  Which version of Firefox do you use ? It works on both of my Chrome and Firefox (v123)

**Comment by LaChope** [comment]
I am using  v122.0.1, I will try different versions and keep you updated

**Comment by LaChope** [comment]
FYI upgrading to v123 did not help
