### ISSUE TITLE
Autocomplete tree with dereferenceable values does not work correctly

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#133]
Tested on A1 form.

![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/649bc3de-ba62-498b-9632-77b12189691f)

**Comment by LaChope** [comment]
I understood the opposite, that it should be set to true to work, my bad.

**Comment by LaChope** [comment]
@blcham It is supposed to work the other way around, if should not be a link if dereferenceable is set to `true` (to not break default behavior). If it does not make sense semantically, we should rename dereferenceable.

**Comment by blcham** [comment]
To me, the name makes sense and the following behaviour:
- `provides-dereferencable-answer-values = true` -- should show links. See [dereferencable URIs](https://www.w3.org/TR/ld-glossary/#dereferenceable-uris). Also it makes sense that this is default value because if you have link in the autocomplete tree it should be clickable.
- `provides-dereferencable-answer-values = false` -- only if you do not want to allow links

**Comment by LaChope** [comment]
I cannot find it written in ticket, but we discussed having it this way to keep the default behaviour of intelligent-tree (always show as link). But, if you think it is better this way, I will change it.

**Comment by blcham** [comment]
I found only this comment: https://github.com/kbss-cvut/s-forms/pull/263#discussion_r1472540999
