### ISSUE TITLE
Update excel for importing failure reports in record manager

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/record-manager-ui#142]

**Comment by kostobog** [comment]
@blcham 
I added column `7. Repeated failure` to table failure-records-template.xlsx and failure-records.xlsx .
The origin allows adding values YES  or  NO and has origin IRI (see hidden row 4) `http://onto.fel.cvut.cz/ontologies/ava-study/model/repeated-failure`.

**Comment by blcham** [comment]
@kostobog it is typeahead option, so why not doing same as in other typeahead options.

BTW, to match label, we need to have same label, i.e.:
YES --> Yes 
NO --> No

**Comment by blcham** [comment]
thanks, still issue with possible values, which @blcham will fix
