### ISSUE TITLE
React Intl object not found when opening new form

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#150]
When I open new form I get following error:
![image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/8180cdef-1869-4802-9950-25962a590c85)

**Comment by blcham** [comment]
The issue seems to be merge of https://github.com/kbss-cvut/s-forms/pull/332 and particularly the commit https://github.com/kbss-cvut/s-forms/pull/332/commits/f4fd2760fecb7caa99dbd680f5d57e08ed1bef71.

**Comment by LaChope** [comment]
I cannot reproduce the error. I tried to open different forms in s-forms, the aircraft form in record-manager-ui and also on https://kbss.felk.cvut.cz/ava/failure-record-manager/

**Comment by blcham** [comment]
@LaChope try specific version of s-forms that was reverted.

**Comment by blcham** [comment]
Relates to https://github.com/kbss-cvut/s-forms/issues/193.
