### ISSUE TITLE
Add filtering for "Template" column

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/record-manager-ui#168]
@blcham

**Comment by blcham** [comment]
Requires first implementation at backend

**Comment by blcham** [comment]
@LaChope backend was implemented here: https://github.com/kbss-cvut/record-manager/pull/51

here is an example of how to use the new query parameter: 
`....&formTemplate=http://example.org/template-1&formTemplate=http://example.org/template-2`

**Comment by blcham** [comment]
@LaChope i am done with backend
