### ISSUE TITLE
It should not be possible to navigate in records if the count is not reached

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/record-manager-ui#171]
![Image](https://github.com/kbss-cvut/record-manager-ui/assets/57750426/f95c7001-3e9c-46d7-9565-f98a2401a6ee)

**Comment by LaChope** [comment]
@blcham

**Comment by blcham** [comment]
works correctly at KBSS.

![image](https://github.com/user-attachments/assets/bdbadd1b-3b5e-47cb-9070-47a6f224643f)
