### ISSUE TITLE
Refactor the way how JSON-LD is processed in template filter

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#173]
For code:
```
    for (const t of formTemplates) {
      templatesWithLabelAndValue.push({
        value: t["@id"],
        label: t["http://www.w3.org/2000/01/rdf-schema#label"][0]["@value"],
```

we need to use something like 
```
JsonLdUtils.getJsonAttValue(item, Vocabulary.RDFS_LABEL)
```

_Originally posted by @blcham in https://github.com/kbss-cvut/record-manager-ui/pull/172#discussion_r1633090303_

**Comment by palagdan** [comment]
@blcham,

I'm facing an issue when trying to use the JsonLdUtils package in my code. It appears to be undefined when I log it (console.log(JsonLdUtils)), and as a result, I can't call any methods from it. Have you seen this before, or do you know how to fix it?

I've tried reinstalling the package using rm -rf node_modules and npm install, but that didn't resolve the issue.
