### ISSUE TITLE
Import better sample data of failure records

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#174]
Will be done based on:
https://docs.google.com/spreadsheets/d/1DnTBad2br-5UgDaks3tF3SXQMxxllil9/edit?gid=440581771#gid=440581771

**Comment by blcham** [comment]
@kostobog please modify https://docs.google.com/spreadsheets/d/1DnTBad2br-5UgDaks3tF3SXQMxxllil9/edit?gid=440581771#gid=440581771

**Comment by kostobog** [comment]
@blcham 
Testing data is uploaded in the GD file specified above.

**Comment by blcham** [comment]
Data were imported and are available in slack as mentioned https://github.com/kbss-cvut/ava-analytics-ui/issues/41#issuecomment-2194691736
