### ISSUE TITLE
Have posibility in RM to complete set of records

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#18]
![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/098e2278-1849-4a47-9a20-5fa38701300f)

Roles:
- OU - operator regular user
- OAU - operator admin user
- SAU - supplier admin user 

Scenario is:
1) OU edits + save records -- he can see in list of records that this record is not complete
2) OU complete-s records -- he hits a button next to Save button called "Complete/Close record"
3) OAU can see which records are completed/not completed and there is a button "Publish" to publish all the completed records
4) SAU - opens records sent by OAU (BTW, all of the records are again not completed)
5) SAU edits + save records -- he can see in list of records that this record is not complete
6) complete-s/reject records -- he hits a button next to Save button called "Complete/Close record" or "Reject record"
3) OAU can see which records are **completed/not completed/rejected** -- i would call completed --> accepted

The idea:

![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/c942ca05-f7d3-4a26-a57c-fb61a8755802)

OU/OAU will see:

![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/b9a8bfca-5273-4c01-a80c-7e1269064267)

SAO will see:

![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/2872c99f-7ab2-44f3-87f6-8d15b8476eb0)

**Comment by LaChope** [comment]
Operator Admin (check extension = operator && user = admin):
- Publish Completed Records in Records dashboard

**Comment by blcham** [comment]
@LaChope Implementation on server-side is completed, you should be able to test based on PR -- https://github.com/kbss-cvut/record-manager/pull/31.

Use docker image *:pr-31 instead of *:latest.

**Comment by LaChope** [comment]
@blcham @kostobog I cannot create nor open form when I use this image (see screenshot below), I tried both in admin and regular user.

![image](https://github.com/kbss-cvut/record-manager-ui/assets/57750426/cdb70cff-032b-409b-970e-1f3ee677e930)

**Comment by kostobog** [comment]
I changed the model to work with `enum`. Now records in `json` format can be deserialized when the value of the state property is one of - `"open"`, `"valid"`, `"completed"` and `"published"`.
Unfortunately, I could not test it locally. 
The new version is in kbss-cvut/record-manager#31.

**Comment by LaChope** [comment]
@kostobog I did `docker compose pull` but still had the same issue

**Comment by LaChope** [comment]
> @LaChope Implementation on server-side is completed, you should be able to test based on PR -- [kbss-cvut/record-manager#31](https://github.com/kbss-cvut/record-manager/pull/31).
> 
> Use docker image *:pr-31 instead of *:latest.

@blcham Is the new image of pr-31 deployed?

**Comment by kostobog** [comment]
@LaChope @blcham
Updated kbss-cvut/record-manager#31 resolves the `PatientRecord.state` deserialization issue on the server side. Tested with record manager docker image version `pr-31`.

**Comment by kostobog** [comment]
@LaChope @blcham
Updated kbss-cvut/record-manager#31. Record state is refactored to record phase. 

I tested the record-manager-server image version `pr-31` in `record-manager-ui/deploy/internal-auth/docker-compose.yml`. The record phase is persisted in db-server.

**Comment by LaChope** [comment]
@kostobog It is now working for Record when I GET `/rest/records/xxx` but I also need to get the phase when I retreieve by institution GET `/rest/records?institution=xxx`

@blcham

**Comment by kostobog** [comment]
@LaChope I updated  kbss-cvut/record-manager#31 to return the phase for `/rest/records?institution=xxx`.

**Comment by LaChope** [comment]
> I changed the model to work with `enum`. Now records in `json` format can be deserialized when the value of the state property is one of - `"open"`, `"valid"`, `"completed"` and `"published"`. Unfortunately, I could not test it locally. The new version is in [kbss-cvut/record-manager#31](https://github.com/kbss-cvut/record-manager/pull/31).

@kostobog @blcham I think there is one enum missing `"rejected"`

**Comment by kostobog** [comment]
@LaChope added rejected in kbss-cvut/record-manager#36.

**Comment by blcham** [comment]
@LaChope 
Feedback:

General:
- Completion status --> Status

OU:
- OU should see completion status
- OU should be able to complete the record
- OU cannot do anything with after completed record
   - no save or complete button
   - disabled record (LOW PRIORITY -- can be put to new ticket)

OUA:
- Publish -- Publish Completed Record
- Can save record unless it is already published
