### ISSUE TITLE
Call on record update service

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/record-manager-ui#182]
@blcham 
Call external service on record update
A/C :
- `onRecordUpdateServiceUrl` - record manager can be configured which service to call
- record manager calls the `onRecordUpdateServiceUrl` with the updated record URI on successful PatientRecordController.updateRecord
- if `onRecordUpdateServiceUrl` is not configured do nothing

**Comment by blcham** [comment]
Implemented by https://github.com/kbss-cvut/record-manager/pull/57
