### ISSUE TITLE
Unable to save record in keycloak deployment

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#187]
When running record-manager from `deploy/keycloak-auth` I cannot save an form. I get error:
![image](https://github.com/user-attachments/assets/f247f158-767a-45f6-a3f7-0d3949fa9847)

**Comment by blcham** [comment]
FYI @palagdan

**Comment by palagdan** [comment]
@blcham 

I cannot simulate this problem. The updated Docker image may have fixed it.

**Comment by blcham** [comment]
Cannot be reproduced.
