### ISSUE TITLE
It was possible to save record with 2 different times of modification

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#199]
This happened when installing a new version of AVA SW when creating the first record (? maybe with a user not belonging to an institution ?)

**Comment by blcham** [comment]
Most-likely the scenario:
1) start with user without institution
2) create record
3) try to save it to show validation messages
4) fill in record and try to save again -- now it says error you do not have institution assigned
5) assign user to institution
6) save (? maybe even hit complete ?)
7) BUG: records won't be loaded because there are 2 modification times

**Comment by blcham** [comment]
@kostobog i did not manage to reproduce the issue

**Comment by palagdan** [comment]
unable to reproduce
