### ISSUE TITLE
Only publish complete records

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/record-manager-ui#207]
@blcham 
Fix publish button behavior to comply with the following requirements:
- [x] publish only records with complete phase
- [x] change the record phase to `published` on records that were actually published.

**Comment by blcham** [comment]
![image](https://github.com/user-attachments/assets/02850712-2b3a-47e5-a40a-d90f9b25327d)

**Comment by blcham** [comment]
Resolved.
