### ISSUE TITLE
Resolve dependencies suggested by dependabot

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#227]
![image](https://github.com/user-attachments/assets/6c209566-b5b3-4b74-8803-aa9d2510f277)

See also:
- https://getbootstrap.com/docs/5.0/migration/
- https://github.com/kbss-cvut/s-forms/pull/352

A/C:
- all dependencies are upgraded or argumented why not upgrade them

**Comment by blcham** [comment]
@palagdan do not upgrade Bootstrap, as I predicted, there is an issue with that, see https://github.com/kbss-cvut/s-forms/issues/362

**Comment by palagdan** [comment]
@blcham 
I've updated and tested all dependencies(not Bootstrap), they work correct in RM.  

I will read the migration guide for bootstrap and try to resolve the problems with the styles.

**Comment by blcham** [comment]
@palagdan, shouldn't the upgrade be done to SForms as well?

**Comment by palagdan** [comment]
@blcham 

Yes, the bottom margin should be fixed
![s-forms-update](https://github.com/user-attachments/assets/59598d64-dad1-4666-a3ac-f5eb3e6cfc01)

**Comment by blcham** [comment]
Closing as all deps were resolved while bootstrap will be handled in https://github.com/kbss-cvut/record-manager-ui/pull/215.
