### ISSUE TITLE
USER/ADMIN role in Record manager vs. in Keycloak

### ISSUE THREAD

**Issue by grotskat** [kbss-cvut/record-manager-ui#246]
In Keycloak the role is **Admin** and in Record manager the role is **User**. However, the function of Record manager is correct, i.e. **Admin**. This happens when changing the role, but also when creating a new role in Keycloak.

![image](https://github.com/user-attachments/assets/176d7b96-ece1-450c-a807-ebf4251232e5)
![image](https://github.com/user-attachments/assets/1df966e8-6ecd-4d63-90ef-ff27298856cf)

**Comment by palagdan** [comment]
@blcham 
Seems like a duplicate issue. See https://github.com/kbss-cvut/record-manager-ui/issues/158.

**Comment by blcham** [comment]
@grotskat as it is a duplicit issue, closing this one in favor of #158
