### ISSUE TITLE
It is not possible to create record as Admin

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#25]
![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/fd251924-6c5f-4daa-8849-48760fc83deb)

**Comment by blcham** [comment]
You can debug using: 
23ava-distribution/supplier-ava
record-manager-ui/deploy/internal-auth

**Comment by kostobog** [comment]
I did not fix this yet!? It does not work for me locally.
@blcham

**Comment by blcham** [comment]
thanks, I mis-clicked here -- I meant different ticket.
