### ISSUE TITLE
Migrate to react 18

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#3]
The goal is to migrate record-manager-ui from React 17 to React 18.

Note that related repositories were already migrated to React 18:
- https://github.com/kbss-cvut/s-forms  (dependency)
- https://github.com/kbss-cvut/s-forms-demo (demo application using s-forms)

A/C:
- [x] package.json sets react dependency to version 18
- [x] it is possible to log in to the application, create and save a record
- [x] application works in [provided dockerized version](https://github.com/kbss-cvut/record-manager-ui/blob/main/deploy/internal-auth) as well
- [ ] at least in development deployment, it is possible to browse sources from the development console

Regarding the work related to https://github.com/akaene/record-manager-ui/tree/fix/akaene-migration-18 we need to do:
- remove .env
- remove formatting changes
- remove `npm run server` script from package.json
- fix CSS styles so they are working the same as in version 17 within records

**Comment by LaChope** [comment]
**Failure Mode:** The specific manner or way by which a failure occurs in terms of failure of the part, component, function, equipment, subsystem, or system under investigation.

Example: Failure of van -> Failure Modes: 
- Van stuck open
- Van stuck closed
- Van stuck middle

**Comment by LaChope** [comment]
@blcham 
might be a beginning of solution here: https://hinty.io/devforth/fix-webpack-imported-module-is-not-a-function-for-webpack5/

**Comment by LaChope** [comment]
Interesting findings:
- When using jsonld-utils from version 0.1.1 in **s-forms**, I get the similar error as in record-manager-ui 

![image](https://github.com/kbss-cvut/record-manager-ui/assets/57750426/00cfaf49-8a82-422e-93f2-d01feab392fa)

**Comment by ledsoft** [comment]
@LaChope 
Please, try the following:
1. Update to jsonld-utils 0.1.2 (https://kbss.felk.cvut.cz/dist/jsonld-utils-0.1.2.tgz)
2. Replace all occurrences of `import JsonLdUtils from "jsonld-utils"` to `import * as JsonLdUtils from "jsonld-utils"` (note that in `Answer.jsx`, the import is called `JsonldUtils`) in s-forms

**Comment by blcham** [comment]
@LaChope otherwise try to put everything from jsonld-utils into SForms

**Comment by LaChope** [comment]
@ledsoft New version of jsonld-utils is working, there is no import issue anymore.

@blcham FYI it was likely due to caching issue, after invalidating cache of Intellij it worked

**Comment by blcham** [comment]
@LaChope try to see how it works if you merge with current main

**Comment by LaChope** [comment]
@blcham @shellyear
Hints about testing: record-manager-ui is using jest and enzyme-adapter for react. Enzyme also had to be updated to support react 18 https://github.com/cfaester/enzyme-adapter-react-18. According to the author, only the `simulate` function might cause issues, but I did not get to the point where I run tests so I do not know if there are some other implementation issues.
For reference, I ran tests on main branch (`1f02b458`) and all tests passed (some are skipped).

Later in the future, I recommend to drop enzyme and take another testing solution that is supported such as [react-testing-library](https://testing-library.com/docs/react-testing-library/intro/)

**Comment by blcham** [comment]
@shellyear

Currently, the migration works for WizardLess forms such as "Form example 1" and "Form example 2". However, it does not work for forms with Wizard. The issue might be way how it is implemented in SForms, see https://github.com/kbss-cvut/s-forms/blob/4004c71e4d97e7b225b53b79214a02224e009cd7/src/components/FormManager.jsx#L75

**Comment by blcham** [comment]
@shellyear @LaChope please, if u have any ideas comment it here

**Comment by LaChope** [comment]
@blcham before migrating to Vite, we need to make sure it will work with complex paths (tbh I think it will work but still we need to make sure)

**Comment by blcham** [comment]
As can be read above, the remaining issues are:
- failing tests are disabled
- DateTimeAnswer causes application to crash
