### ISSUE TITLE
Support export to CSV/Excel

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#36]
Notes:
- if possible we should inject lines into Excel
- possible values for aircraft should be taken from fragment of URL or path of labels

A/C:
- [x] implement backend
- [ ] implement frontend

**Comment by blcham** [comment]
@LaChope https://github.com/kbss-cvut/record-manager/pull/52#discussion_r1672286344

**Comment by kostobog** [comment]
@blcham
The current solution does not work when exporting with a bigger data set.
