### ISSUE TITLE
Support for import of records from json

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#38]
As a user of RM I would like to import data containing records in JSON format. I can import data as $REGULAR_USER or $ADMIN. 

**Imported data should have following properties:**
- URIs of entities should be taken from the JSON
- there si proper error shown if there is collision of URIs (e.g. IRIs of records, questions or answers already exists)
- only records that does not have collision of IRIs can be imported 

**In addition when executed by $REGULAR_USER:**
- author of each record should be changed to the $REGULAR_USER
- record phase of imported records should be set to "open-record-phase" 

**In addition when executed by $ADMIN:**
-  if there is a record that references not-existing user/institution, import should fail

------
**Implementation detail:**
- REST API could have attribute `record-phase` which would be called with value `open-record-phase` in case of $REGULAR_USER

-----

**A/C:**
- there is a single "Import" button for ADMIN view and REGULAR_USER view, however it imports record differently as described above

**Comment by blcham** [comment]
@ledsoft

**Comment by ledsoft** [comment]
@blcham What about the institution of the records? I assume the current user's institution is used?

**Comment by blcham** [comment]
Yes.
