### ISSUE TITLE
Context menu is not shown when clicking on user's name

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#56]
From time to time, context menu is not shown when clicking on user's name (By context menu i mean menu that is shown when i click with left mouse button).
![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/49134d99-b2fa-42be-842f-6a2d47a02900)

 
Same bug occurs when I hit export button: 
![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/3d79b3db-3561-4023-a6e1-68ba9773e98b)

It seems that following steps can be used to simulate the issue:
1) make an action that triggers user notification 
2) [BUG] "clicking on user's name" should not work anymore
![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/d8993447-b33b-4353-ba48-00d4bcd3b35f)

**Comment by blcham** [comment]
- by context menu i mean menu that is shown when i click with left mouse button

**Comment by ledsoft** [comment]
Apparently caused by https://github.com/react-bootstrap/react-bootstrap/issues/5409
