### ISSUE TITLE
Record state is not properly cleared when opening record

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/record-manager-ui#62]
When I:
- save a record
- go to list of records
- create new record i get following message ("Fro) at the button of edit-record view:
 

![Image](https://github.com/kbss-cvut/record-manager-ui/assets/3962237/009a2117-c62b-4108-8098-70803d4f527e)

Thus it seems like record is not properly cleared and record component state is leaking from previous record.

**Comment by ledsoft** [comment]
IMO not relevant anymore thanks to #77.

**Comment by blcham** [comment]
I agree.
